FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY installer/ /usr/src/app/installer/
COPY gulpfile.js installer/package.json /usr/src/app/
RUN npm install
RUN chown -R node /usr/src/app
USER node
